### ISSUE TITLE
User fonts not worked

### ISSUE THREAD

**Issue by DimonSmart** [dukelec/mb#10]
I'm trying to use a custom font. For example: https://www.fonts-online.ru/fonts/cyrillic
It show my font correct on text edit box. But after finish editing text changed to default font.
Next. After upload my fonts only presented while I'm editing. After quit and start a new edit my fonts disappeared.

**Comment by dukelec** [comment]
Thank you for your feedback, I got the same result which you said.
I found a common for the problem: the font file's name is starting by number, when I rename the font to begin with letter, it was fine.
This issue will be fixed soon.
