### ISSUE TITLE
Speed Up Conversion Process

### ISSUE THREAD

**Issue by chonigman** [dukelec/mb#21]
Hi. I'm not sure if this is possible but is there a way that the conversion process for the image slices can be sped up at all? We are using the printers in a large installation with many thousands of images and conversion time is around 15seconds for three slices. I've tried to pick apart the code that converts but it is a little opaque to me. If there is no way to speed it up programmatically, are there contributing factors that cause the conversion to take more or less time?

Thanks.

**Comment by dukelec** [comment]
Sorry for the late reply, I forgot that this issue did not reply.

I think it is difficult to increase the conversion speed. The current conversion is the C language code running through WASM in the browser, which is not much different from the efficiency of running the C code directly.

The image converted in the middle process is very large. For example, when printing with a size of 100 mm x 14.29 mm, the pixel corresponding to 14.29 is fixed at 684 dot (and fixed at 1200 dpi). If 100 mm corresponds to a resolution of 600 dpi, then it's 684×100÷14.29÷2 ≈ 2393 dot. In other words, it is time-consuming to convert the original PNG image into a 2393 x 684 color image, which also involves various algorithms such as rotation and dithering. If you want to be faster, you can try 1200 x 300 dpi.

Moreover, the printer can start working without waiting for all the pictures to be converted, as long as the picture currently to be printed is ready.

Finally, the C source code of the conversion tool may be released soon, and I am considering it. I am not sure if you need it.

**Comment by MarcWeber** [comment]
There are eventually indeed some ways but might have different quality:
- use browsers graphic engine which might have access to the graphic hardware: Eg add images / css then get canvas as image
- compile c code to JS, use JS workers (multiple cores), or https://blog.scottlogic.com/2019/07/15/multithreaded-webassembly.html 
I have never tried that, though.

gegl/babl is open source and might give quick hints whether speed can be increased.

Somehow this reminds me of the old days with postscript and printer having had biggest RAM/CPU.

There was some way to access graphic cards using Flash, but that's dead.

https://stackoverflow.com/questions/11112321/how-to-save-canvas-as-png-image.

Another question is does it make sense to send SVG to printer, and have printer render on the fly. For simple things like simple fonts / rects / simple graphics might be faster than converting png (but I don't know) or postscript.

**Comment by dukelec** [comment]
The C source code for the conversion tool has been uploaded.

**Comment by chonigman** [comment]
Thanks for the continued support. We were able to make it work for our project.
