### ISSUE TITLE
Printing half a line

### ISSUE THREAD

**Issue by IonPurple** [dukelec/mb#24]
MBrush only prints half a line. Consistently good, but only a half of it. See fig. 1.
![image](https://user-images.githubusercontent.com/73240932/96776157-4aeca180-13f1-11eb-8eee-c9ae59ddedbb.png)
Can anything be done?

**Comment by farfadet46** [comment]
just clean your printer (you can press a long time on the button) if nothing change, try alccool.

**Comment by IonPurple** [comment]
> just clean your printer (you can press a long time on the button) if nothing change, try alccool.

Long press on the button essentially does the same thing - it only prints half of the line.
Where do I apply the alcohol - to the contacts on each side?

**Comment by dukelec** [comment]
It's a Poor contact issue, please visit: "Poor contact" section of https://blog.d-l.io/mb-faq

**Comment by IonPurple** [comment]
> It's a Poor contact issue, please visit: "Poor contact" section of https://blog.d-l.io/mb-faq

Did that too. Even disconnecting, cleaning and re-connecting a flat-wire to the interface didn't work. Unless I have to also clean the interface, but I've got no idea how would I do that without messing it up

**Comment by dukelec** [comment]
Please try using a small blade instead of an eraser to scratch the surface of the ink cartridge contact points. If it still fails, please contact the after-sales replacement.

To be sure, the vast majority of this problem is caused by poor contact of the ink cartridges.

**Comment by IonPurple** [comment]
Did try that too, also did try to clean up the contact circles from the eraser shreds with a toothpick. Nada.

**Comment by IonPurple** [comment]
Now negotiating a refund or replacement. Thank you for your help.

Your troubleshooting guide is very thoughtful and thorough, however what I have here appears to be something that can't be fixed that easily.

**Comment by necros2k7** [comment]
@IonPurple  is it the same issue I have ? - trying to print added text "post" x1 size - all prints ok but 1st letter "p" is cut and printed like "o", is it contact issue or printer?
