### ISSUE TITLE
Mbrush App link does not work

### ISSUE THREAD

**Issue by molangy29** [dukelec/mb#26]
In August when I tested my mprinter it worked. And now, the page APP that lets me enter in the text/picture to the printer doesn't work so I can't use my printer. HELP! I am not good with understanding what is going on so please simplify. I tried resetting my router, had family in other states try but don't think it works in America. What is going on? HELP.

![Site cant be reached](https://user-images.githubusercontent.com/73378527/97069502-765cc100-1596-11eb-882c-f040e9ac3c13.JPG)

**Comment by dukelec** [comment]
It's nothing to do with your router, you should connect your phone or laptop to the MBrush's Wi-Fi directly.

Please checkout "WiFi connection issues" of the FAQ first: https://blog.d-l.io/mb-faq

**Comment by molangy29** [comment]
Sorry - let me clarify - the issue is the QR code and the link 192.168.44.1 both do not work when I try to put it into the web address. The page itself is not working so I don't have an app to create my text to be printed even though my wifi does connect. 

Is the actual page opening up for you?

**Comment by molangy29** [comment]
The QR code worked again today. Just tried it successfully this time! Thank you for the quick response! You are awesome.
