### ISSUE TITLE
upload cgi script seems to be mising Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by MarcWeber** [dukelec/mb#45]
printf("Access-Control-Allow-Origin: *\n");
might be enough to add after setcontenttype cause the qdecode doesn't seem to have a add_header method or such.

I tried mips compiler form ubuntu, yielding:
```
originial file output
ELF 32-bit LSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, interpreter /lib/ld.so.1, for GNU/Linux 2.6.32, with debug_info, not stripped
new file output
ELF 32-bit MSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, interpreter /lib/ld.so.1, BuildID[sha1]=98439f67c2ea9cbf6087a1a73182af3df3a4880a, for GNU/Linux 3.2.0, with debug_info, not stripped
```
but looks like its for newer gnu linux version ?
Result is '404 not found' using the cmd= to run it it yields syntax error ( or such (?) wheras the original just says status err filename ro length empty as expected.

Is there any hint about how to setup this cross compilation toolchain ?

**Comment by dukelec** [comment]
You need to add additional `-EL` parameters to generate little-endian programs, because the CPU is little-endian.

The vendor's GCC is already enabled for little-endian by default when it is compiled, so you don't need to specify it.

If that doesn't work, maybe you can try: https://github.com/Dafang-Hacks/mips-gcc520-glibc222-64bit-r3.2.1

**Comment by MarcWeber** [comment]
The printer I uploaded the wrong upload file does no longer connect to either USB/WIFI. It doesn't start WIFI. Even if the upload executable is bad, the cmd command should still be working (?). Resetting by staring and holding the button doesn't fix. Printing the standard image still works. Is there another way to reset/flash the chip or did the hardware turn faulty thus need to get new device ?

**Comment by dukelec** [comment]
If the factory firmware is a bit old, you cannot restore the factory firmware by restoring the factory settings, but even so, you can still burn the latest firmware via USB: https://github.com/dukelec/mb/issues/18

Or, you can log in to the printer through the TTL serial port, check the cause of the error, and then try to fix it.

**Comment by MarcWeber** [comment]
Couldn't get Windows to work [start] no progress. On Ubuntu first boot cell 100%, next boot cell INIT ERR. So looks like a hardware problem then.

````
"32:51" cloner (init)message: "4:0:-1:6:60" 
"32:51" core (int)message: "4:0:-1:6:70;" 
"32:51" cloner (init)message: "4:0:-1:6:70" 
"32:51" core (int)message: "4:0:-1:6:75;" 
get flash info: 0
"32:51" core (int)message: "4:0:-1:6:80;" 
"32:51" cloner (init)message: "4:0:-1:6:75" 
"32:51" cloner (init)message: "4:0:-1:6:80" 
"32:51" core (int)message: "4:0:-1:6:90;" 
&&&&&&&&&&&&&&bootrom_security_en: 0
"32:51" cloner (init)message: "4:0:-1:6:90" 
"32:51" core (int)message: "4:0:-1:6:100;" 
"32:51" cloner (init)message: "4:0:-1:6:100" 
"32:51" core (string)message: "4:0:0:7:INIT ERR;" 
"32:51" core (int)message: "4:0:0:8:-1;" 
"32:51" cloner (init)message: "4:0:0:7:INIT ERR" 
"32:51" cloner (init)message: "4:0:0:8:-1"
```

Board version MB 4.2.
Thing is I was able to try running upload but it failed. So everything was still working. No idea what happened so don't think it's related to my try to upload modified firmware.

**Comment by dukelec** [comment]
I feel that the error is the wrong file path, or the wrong config selection.

Please check. If it doesn't work, please provide some screenshots.

**Comment by MarcWeber** [comment]
https://mawercer.de/tmp/tmp/pc/ see images here. I double checked that the screens from #18 look the same.

**Comment by dukelec** [comment]
Please provide me with the dmesg information of the kernel further.
(You can open a terminal and enter the command: `dmesg -w` before testing)

Is the linux system the primary system? Or is it in the virtual machine of the windows system?

**Comment by MarcWeber** [comment]
Same directory. I"ve been running Ubuntu natively on 2 machines (dekstop/laptop) trying front/back USB. Same result. dmesg both machines see same http directory.
In case case I now got an IO error and no 100% first boot cell - should be contained in dmesg second attempt same result as on screenshots. Third try laptopt same

**Comment by dukelec** [comment]
I tried again, there should be a problem with the file path.

The original path is tools, and the device can be burned normally:
![Screenshot_2021-11-04_00-35-02](https://user-images.githubusercontent.com/4454365/140104345-26a4a217-e618-431b-b63f-0e80b183da2e.png)

After renaming the tools directory, I got the same error as you did:
![Screenshot_2021-11-04_00-34-03](https://user-images.githubusercontent.com/4454365/140104372-e79f7d78-e268-4d94-86e6-d876d24c9332.png)

Please make sure that you have selected the path correctly:
![Screenshot_2021-11-04_00-35-47](https://user-images.githubusercontent.com/4454365/140104398-f71eb079-206f-4fbd-8299-72ab431d76ce.png)

The path should ensure that the program has access rights, and the path should be free of spaces and characters other than ASCII.

**Comment by dukelec** [comment]
Try plugging in the usb first, then powering on the device (while holding down the button), so that the usb enumeration is less prone to errors.
