### ISSUE TITLE
provide build / flash instruction

### ISSUE THREAD

**Issue by gasolin** [dukelec/mb#5]
Great to see the PrinCube code is open-sourced, 

it will be nice if you can provide a basic build / flash instruction, so more people can help.

**Comment by dukelec** [comment]
OK, I will add related documents.

It's very simple, just go to the `tools/` directory and execute `./release_fw.sh` to generate a firmware upgrade tarball. (Currently only tested on Linux systems, other systems should also work.)
```
github_mb/tools $ ./release_fw.sh 
version: 4.26_4.11, APP: 4.26
brand: PrinCube
github_mb/tools $ ls *.tar
PrinCube-fw-4.26_4.11.tar
```

At the bottom of the APP Setting page, select the tarball and upload it to update the firmware.
