### ISSUE TITLE
Where to buy

### ISSUE THREAD

**Issue by bmuessig** [dukelec/mb#50]
Hello, I'd love to buy a PrintCube. I absolutely love your support and that you have open sourced the code.

Is this the legit site to buy it from? https://www.thegodthings.com

BR,
Benedikt

**Comment by dukelec** [comment]
The mbrush and the princube are the exact same hardware and should be able to find some sellers on Amazon.

**Comment by bmuessig** [comment]
Thanks for the answer, but Germany it does not seem to be available. Do you know the seller The God Things?

**Comment by bmuessig** [comment]
@dukelec I'd much appreciate if you could shed some light on where to buy it. You're the only official person on the product to ask at this point. After a bit of research, I have no idea what websites scam you and which won't.
TheGodThings claims that all other stores are fake and I would believe them, because they appear to have developed the product as part of their Indiegogo campaign. Though many backers and people who ordered from the website claim that they have never received anything. I could order the MBrush from China from eBay, but it's quite a lot more expensive.
What is going on? I am really confused at this point.

**Comment by t-legiaw** [comment]
@bmuessig 

> in Germany it does not seem to be available
I bought mine here: https://www.kaufland.de/product/358517505/

**Comment by bmuessig** [comment]
> @bmuessig
> 
> > in Germany it does not seem to be available
> 
> I bought mine here: https://www.kaufland.de/product/358517505/

Thank you
