### ISSUE TITLE
coud not send file to print from CURL or POST

### ISSUE THREAD

**Issue by leccyril** [dukelec/mb#61]
i am trying this part of code

```
/cgi-bin/upload
Upload file to /upload/

Shell command example:

curl -F "pos=0" -F "file=@0.mbd" http://192.168.44.1/cgi-bin/upload, or:
curl -F "file=@0.mbd" http://192.168.44.1/cgi-bin/upload
```
but with post, result is 200 but nothing appears in the home page , could not send file to print with DEV API ? (is this command is for file to print ? or for something else ?)

if yes how ? if no could it implemented because it will be really great in association with local network connecion !

**Comment by dukelec** [comment]
The commands you quoted are send print data to the printer, it's nothing to do with the app home page.

**Comment by leccyril** [comment]
Yes but it should be available on home page where project are registered ?, i saw that i hav to send mbd file so maybe it is the issue, how we can convert jpg or png in mbd file with curl ?

**Comment by dukelec** [comment]
The print data only transfer from app to printer, not support read back from printer to app.
png file can't send direct to the printer, you should convert png file to mbd first, see the dev document.
You should press the print button on the printer to start printing, or use the button simulation api instead.

**Comment by leccyril** [comment]
Ok so i create a mdb file form app and export it, then i upload on printer

http://10.0.4.36/cgi-bin/upload (with file= and my file)

http://10.0.4.36/cgi-bin/cmd?cmd=rm_upload
http://10.0.4.36/cgi-bin/upload
http://10.0.4.36/cgi-bin/cmd?cmd=sync
http://10.0.4.36/cgi-bin/cmd?cmd=get_info

then when i click on printer button 2 fast bip and then nothing is printed.

when i test same file from the browser 2 bips then 1 big bip and green alert, then it prints...

Any idea ?

**Comment by dukelec** [comment]
Try put your 0.mbp in current path, invoke curl command without path string.

Try follow command each step to check whether your file upload succeeded or not:
http://192.168.44.1/cgi-bin/cmd?cmd=eval&val=ls -l /root/mb_ser/upload/

**Comment by leccyril** [comment]
ok so first i delete all files

![image](https://user-images.githubusercontent.com/3234598/202084360-067247df-458d-41d7-8758-ab2643d3a899.png)

then i upload file name 0.mbp

![image](https://user-images.githubusercontent.com/3234598/202084415-2919d1d0-8e7d-4753-94a2-2fbb1667fc1f.png)

then i check if file is uploaded

![image](https://user-images.githubusercontent.com/3234598/202084493-603cd1e9-de37-48aa-8e48-2443be12aec7.png)

file is present => then i try to print nothing happen, when i click i heared 2 small bips white light

**Comment by dukelec** [comment]
mbp: mbrush project
mbd: mbrush data

mbp convert to mbd by the html5 app.
png convert to mbd by the headless convert tool.

Only the data file mbd could send to the printer.
