### ISSUE TITLE
print quality is not good

### ISSUE THREAD

**Issue by golfsburg** [dukelec/mb#8]
hello, I received today my MBrush and everything has benn looking and running good until the first print! There are several mistakes in the print output, see attached. I have been cleaning the nozzle and also updating the firmware but nothing helped! Can you help me? Otherwise I have to send back the MBrush which would make me very sad!

![1AD0CC8B-6C08-42C4-803C-C14FC4A2DEAA](https://user-images.githubusercontent.com/63365821/78815468-9ea51980-79d0-11ea-89e7-e8962f837540.jpeg)

![D868EA89-69DA-482E-826F-033F6E22E793](https://user-images.githubusercontent.com/63365821/78815522-ae246280-79d0-11ea-8152-2615675735cc.png)

THX & BR Peter

**Comment by dukelec** [comment]
Please checkout section "Poor contact" in FAQ first: http://blog.d-l.io/archive/mb-faq/

**Comment by golfsburg** [comment]
Perfect THX!!!!
