### ISSUE TITLE
 My printer does not print

### ISSUE THREAD

**Issue by Arsen198302** [dukelec/mb#9]
My printer does not print.
At first I didn’t print correctly,the colors were wrong.
And then completely stopped typing.
Please Halp me...

**Comment by dukelec** [comment]
Can you provide some pictures?
Also, did you read the FAQ?
FAQ Address: http://blog.d-l.io/archive/mb-faq/

**Comment by Arsen198302** [comment]
![GIF-200430_010537](https://user-images.githubusercontent.com/63429287/80646691-423c9380-8a7e-11ea-8bfb-3ecda360de6c.gif)
